feat(booking): add new fields to passenger data
duffelhq/duffel-api-javascript pull request #258
Opened 2021-10-29 08:53 UTC by matthewp5

- add new loyalty programme fields to the OfferRequestPassenger interface
- validate new loyalty programme fields on order creation

2021-11-02 10:35 UTC, igorp1 approved these changes
LGTM!

2021-11-02 10:35 UTC, igorp1 commented on src/booking/OfferRequests/OfferRequestsTypes.ts
> +  airline_iata_code: string
How about this?
```suggestion
  airline_iata_code: Airline['iata_code']
```

2021-11-03 09:17 UTC, lapa182 requested changes
@matthewp5 could create a unit test to this change, please?

2021-11-05 09:08 UTC, matthewp5 commented on src/booking/OfferRequests/OfferRequestsTypes.ts
> +  airline_iata_code: string
I like it, done!

2021-11-05 15:33 UTC, lapa182 approved these changes

2021-11-05 15:34 UTC, lapa182 commented
Thanks @matthewp5 !

2021-11-05 17:18 UTC, merged